GET http://localhost:3001/books HTTP/1.1
CONTENT-TYPE: application/json

###

POST http://localhost:3001/books HTTP/1.1
CONTENT-TYPE: application/json

{
  "title"
  : "Soldier"
}

###

PUT http://localhost:3001/books/2 HTTP/1.1
CONTENT-TYPE: application/json

{
  "title": "Hacksaw Ridge 2"
}

###

DELETE http://localhost:3001/books/2 HTTP/1.1
CONTENT-TYPE: application/json
